//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikel()
        {
            this.Prognose = new HashSet<Prognose>();
            this.ArtikelBeleg = new HashSet<ArtikelBeleg>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int GTIN { get; set; }
        public double Bestand { get; set; }
        public Einheit Einheit { get; set; }
        public double Nettoeinkaufspreis { get; set; }
        public double Nettoverkaufspreis { get; set; }
        public int LieferantId { get; set; }
        public int WarengruppeId { get; set; }
    
        public virtual Lieferant Lieferant { get; set; }
        public virtual Warengruppe Warengruppe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prognose> Prognose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtikelBeleg> ArtikelBeleg { get; set; }
    }
}
