//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContainer : DbContext
    {
        public DataContainer()
            : base("name=DataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Markt> MarktSet { get; set; }
        public virtual DbSet<Personal> PersonalSet { get; set; }
        public virtual DbSet<Arbeitsvertrag> ArbeitsvertragSet { get; set; }
        public virtual DbSet<Schicht> SchichtSet { get; set; }
        public virtual DbSet<Lieferant> LieferantSet { get; set; }
        public virtual DbSet<Artikel> ArtikelSet { get; set; }
        public virtual DbSet<Prognose> PrognoseSet { get; set; }
        public virtual DbSet<Warengruppe> WarengruppeSet { get; set; }
        public virtual DbSet<Beleg> BelegSet { get; set; }
        public virtual DbSet<Lieferart> LieferartSet { get; set; }
        public virtual DbSet<Rolle> RolleSet { get; set; }
    }
}
