//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prognose
    {
        public int Id { get; set; }
        public string Datum { get; set; }
        public string Abverkauf_soll { get; set; }
        public string Abverkauf_ist { get; set; }
        public int ArtikelId { get; set; }
    
        public virtual Artikel Artikel { get; set; }
    }
}
