//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolleRecht
    {
        public int Id { get; set; }
        public int RolleId { get; set; }
        public int RechtId { get; set; }
    
        public virtual Rolle Rolle { get; set; }
        public virtual Recht Recht { get; set; }
    }
}
